#!/usr/bin/python
'''
Usage: beatroot audio_file [-O] [-o output_file]
'''

import gflags
import os
from google.apputils import app
from m2.beatroot import beatroot

gflags.DEFINE_bool('onsets', False,
                   'Whether to output onsets instead of beats',
                   short_name='O')

gflags.DEFINE_string('output', None,
                     'File for the output. If not defined, it uses stdout.',
                     short_name='o')


FLAGS = gflags.FLAGS


def main(argv):
    if len(argv) < 2:
        print gflags.DocToHelp(__doc__)
        exit()
    beats = beatroot(argv[1], FLAGS.onsets, FLAGS.output)
    if beats is not None:
        for b in beats:
            print b


if __name__ == '__main__':
    app.run()
